// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftN_dFflI4f2M2xyGsex0Eu8R1Fs13MM',
    appId: '1:48762590081:web:7093eb3bbebf7066988e80',
    messagingSenderId: '48762590081',
    projectId: 'chatapp-60ad8',
    authDomain: 'chatapp-60ad8.firebaseapp.com',
    storageBucket: 'chatapp-60ad8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe_Kuiy7hwuAF1PY21HYF6yV5UvKm-nOQ',
    appId: '1:48762590081:android:fd1f21148288689e988e80',
    messagingSenderId: '48762590081',
    projectId: 'chatapp-60ad8',
    storageBucket: 'chatapp-60ad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSvutsBTHjACv4DYnEBuC88Mmn3PiZ4oQ',
    appId: '1:48762590081:ios:2f45bcf378aed378988e80',
    messagingSenderId: '48762590081',
    projectId: 'chatapp-60ad8',
    storageBucket: 'chatapp-60ad8.firebasestorage.app',
    iosBundleId: 'com.raocoders.chatapp.chatapp',
  );
}
